// Auto-generated by scripts/generate-image-data.mjs — do not edit by hand.
// Run: npm run generate-data
export default [
  {
    "src": "DSCF0185.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0188.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0216.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF0247.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0252.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF0272.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0289.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0319.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF0547.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF1058.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF1279.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF1338.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF1340.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF1351.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF1599.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF2002.JPG",
    "aspectRatio": 1.77931
  },
  {
    "src": "DSCF2045.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF2258.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF2417.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF2758.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF2946.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF3210.JPG",
    "aspectRatio": 1
  },
  {
    "src": "DSCF3235.JPG",
    "aspectRatio": 1
  },
  {
    "src": "DSCF3275.JPG",
    "aspectRatio": 1
  },
  {
    "src": "DSCF3358.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF3365.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF3433.JPG",
    "aspectRatio": 1
  },
  {
    "src": "DSCF3451.JPG",
    "aspectRatio": 2.634021
  },
  {
    "src": "DSCF4436.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF4441.JPG",
    "aspectRatio": 0.666557
  },
  {
    "src": "DSCF4465.JPG",
    "aspectRatio": 2.558179
  },
  {
    "src": "DSCF5180.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF5271.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF6869-Enhanced-NR.png",
    "aspectRatio": 2.708399
  },
  {
    "src": "DSCF7049.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7114-Enhanced-NR-1.png",
    "aspectRatio": 1.180048
  },
  {
    "src": "DSCF7354.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7370.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7407.png",
    "aspectRatio": 1.320673
  },
  {
    "src": "DSCF7409.png",
    "aspectRatio": 2.708333
  },
  {
    "src": "DSCF7438.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7441.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7442.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7492.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7506.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7542.png",
    "aspectRatio": 0.651719
  },
  {
    "src": "DSCF7555.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7560.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7565.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7621.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7716.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7775.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7794.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7799.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7809.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF7866.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7922.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7926.jpg",
    "aspectRatio": 0.8
  },
  {
    "src": "DSCF7956.jpg",
    "aspectRatio": 0.565385
  },
  {
    "src": "DSCF7967.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7970.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7974.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF7993.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8020.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8041.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8048.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8053.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8072.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8121.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8125.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8138.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8244.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF8246.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF8332.jpg",
    "aspectRatio": 2.168172
  },
  {
    "src": "DSCF8358.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF8440.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF8456.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF8480.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF8484.JPG",
    "aspectRatio": 1.77931
  },
  {
    "src": "DSCF8973.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF8978.jpg",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF8981.JPG",
    "aspectRatio": 1.77931
  },
  {
    "src": "DSCF8982.JPG",
    "aspectRatio": 1.77931
  },
  {
    "src": "DSCF9136.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF9139.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "DSCF9361.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF9407.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "DSCF9651.JPG",
    "aspectRatio": 1.333333
  },
  {
    "src": "DSCF9764.JPG",
    "aspectRatio": 1.5
  },
  {
    "src": "_DSF7064.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "_DSF7066.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "_DSF7413.JPG",
    "aspectRatio": 2.708661
  },
  {
    "src": "_DSF7446.JPG",
    "aspectRatio": 1
  }
];
